config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/topics')

  resources :topics do
    resources :posts
  end

  resources :userdetails

  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  #relation between topics and post
  has_many :posts
  #has_many :users, through: :posts
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @posts = Post.find_by_topic_id(params[:id])   
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:issue)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= bootstrap_form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.text_area :issue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="row">

<div class="col-md-4">

</div>

  <div class="col-md-4">


			<h1>Editing topic</h1>

			<%= render 'form' %>

			<%= link_to 'Show', @topic %> |
			<%= link_to 'Back', topics_path %>

</div> 

  <div class="col-md-4">
</div>
</div>

app/views/topics/index.html.erb
<div class="row">
  <div class="col-md-2">


  </div>

  <div class="col-md-8">
        <h1>Listing topics</h1>

        <table class="table">
        <thead>
          <tr>
            <th>Issue</th>
            <th colspan="3"></th>
         </tr>
        </thead>

        <tbody>
          <% @topics.each do |topic| %>
            <tr>
              <td><%= topic.issue %></td>
              <td><%= link_to 'Show', topic %></td>

              <!--link to send user to writing path-->


              <!--<td></td>-->

              <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
              <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Topic', new_topic_path %>

  </div>

  <div class="col-md-2">


  </div>

</div>

app/views/topics/new.html.erb
<div class="row">

<div class="col-md-4">

</div>

  <div class="col-md-4">


			<h1>New topic</h1>

			<%= render 'form' %>

			<%= link_to 'Back', topics_path %>


</div> 

  <div class="col-md-4">
</div>
</div>

app/views/topics/show.html.erb
<div class="row">

<div class="col-md-4">

</div>

  <div class="col-md-4">


			<p id="notice"><%= notice %></p>

			<p>
			  <strong>Issue:</strong>
			  <%= @topic.issue %>
			</p>

			<%= link_to 'Write', new_topic_post_path(topic_id: @topic) %>

			<%= link_to 'Edit', edit_topic_path(@topic) %> |
			<%= link_to 'Back', topics_path %>

			

  		<% if @topic.posts.empty? %>
  			This movie has not been reviewed
  		<% else %>	  
       		<p><%= @posts.description %></p>
       		<p></p>
       		<p></p>
       	<% end %>	
      
</div> 

  <div class="col-md-4">
</div>
</div>