config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/topics')

  resources :topics do
    resources :posts
  end

  resources :userdetails

  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/userdetail.rb
class Userdetail < ActiveRecord::Base
	belongs_to :user
  #validates that one user can create just one user details
  validates_uniqueness_of :user_id, :message => "details already exist"

end

app/controllers/userdetails_controller.rb
class UserdetailsController < ApplicationController

  before_action :set_userdetail, only: [:show, :edit, :update, :destroy]

  #User can only edit or destroy its own details
  before_action :correct_user, only: [:edit, :update, :destroy]

  #For user association withuserdetails
  before_filter :has_user, only: [:new, :create]

  protected
  def has_user
    unless (@user=User.find_by_id(current_user))
      flash[:warning] = 'Userdetail must be for an existing user'  

    end
  end

  # GET /userdetails
  # GET /userdetails.json

  public

  def index
    @userdetails = Userdetail.all
  end

  # GET /userdetails/1
  # GET /userdetails/1.json
  def show
  end

  # GET /userdetails/new
  def new
   @userdetail = Userdetail.new
   
  end

  # GET /userdetails/1/edit
  def edit
  end

  # POST /userdetails
  # POST /userdetails.json
  def create

    @userdetail = Userdetail.new(userdetail_params)

    @user.userdetail= @userdetail
   
    #@userdetail.user_id = current_user.id

    respond_to do |format|
    

      if @userdetail.save
        format.html { redirect_to @userdetail, notice: 'Userdetail was successfully created.' }
        format.json { render :show, status: :created, location: @userdetail }
      else
        format.html { render :new }
        format.json { render json: @userdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userdetails/1
  # PATCH/PUT /userdetails/1.json
  def update
    respond_to do |format|
      if @userdetail.update(userdetail_params)
        format.html { redirect_to @userdetail, notice: 'Userdetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @userdetail }
      else
        format.html { render :edit }
        format.json { render json: @userdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userdetails/1
  # DELETE /userdetails/1.json
  def destroy
    @userdetail.destroy
    respond_to do |format|
      format.html { redirect_to userdetails_url, notice: 'Userdetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userdetail
      @userdetail = Userdetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userdetail_params
      params.require(:userdetail).permit(:first_name, :last_name, :myuserid, :birthday, :gender, :contact_number, :address, :country, :state, :city, :gre_date)
    end

    def correct_user

      @user = @userdetail.user_id

      redirect_to( userdetails_url) unless @user == current_user.id
    end
end

app/helpers/userdetails_helper.rb
module UserdetailsHelper
end

app/views/userdetails/_form.html.erb
    <%= bootstrap_form_for(@userdetail) do |f| %>
      <% if @userdetail.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@userdetail.errors.count, "error") %> prohibited this userdetail from being saved:</h2>

          <ul>
          <% @userdetail.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

              

              
                <%= f.text_field :first_name %>

             
             
            
                <%= f.text_field :last_name,  class: 'form-control input-lg' %>
              
              
                 <%= f.text_field :myuserid, label: "User ID"%>
              
             
                <%= f.date_select :birthday%>
              
              
                <%= f.text_field :gender %>
              
                <%= f.text_field :contact_number %>
             
               
                <%= f.text_area :address %>
             
               
                <%= f.text_field :country %>
              
                
                <%= f.text_field :state %>
              
                <%= f.text_field :city %>
              
                <%= f.date_select :gre_date %>
             
              
              <%= f.hidden_field :user_id %> 

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

app/views/userdetails/edit.html.erb
<div class="row">

	<div class="col-md-4">

	</div>

  <div class="col-md-4">


		<h1>Editing userdetail</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @userdetail %> |
		<%= link_to 'Back', userdetails_path %>


  <div class="col-md-4">
  
  </div>
</div>

app/views/userdetails/index.html.erb
<h1>Listing userdetails</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>User ID</th>
      <th>Birthday</th>
      <th>Gender</th>
      <th>Contact number</th>
      <th>Address</th>
      <th>Country</th>
      <th>State</th>
      <th>City</th>
      <th>Gre date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userdetails.each do |userdetail| %>
      <tr>
        <td><%= userdetail.first_name %></td>
        <td><%= userdetail.last_name %></td>
        <td><%= userdetail.user_id %></td>
        <td><%= userdetail.birthday %></td>
        <td><%= userdetail.gender %></td>
        <td><%= userdetail.contact_number %></td>
        <td><%= userdetail.address %></td>
        <td><%= userdetail.country %></td>
        <td><%= userdetail.state %></td>
        <td><%= userdetail.city %></td>
        <td><%= userdetail.gre_date %></td>
        <td><%= link_to 'Show', userdetail %></td>
        <td><%= link_to 'Edit', edit_userdetail_path(userdetail) %></td>
        <td><%= link_to 'Destroy', userdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userdetail', new_userdetail_path %>

app/views/userdetails/new.html.erb
<div class="row">

	<div class="col-md-4">

	</div>

  <div class="col-md-4">

		<h1>New userdetail</h1>


		<%= render 'form',userdetail: @userdetail  %>


		<%= link_to 'Back', userdetails_path %>


  <div class="col-md-4">
  
  </div>
</div>

app/views/userdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @userdetail.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @userdetail.last_name %>
</p>

<p>
  <strong>User ID:</strong>
  <%= @userdetail.user_id %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @userdetail.birthday %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @userdetail.gender %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @userdetail.contact_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @userdetail.address %>
</p>

<p>
  <strong>Country:</strong>
  <%= @userdetail.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @userdetail.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @userdetail.city %>
</p>

<p>
  <strong>Gre date:</strong>
  <%= @userdetail.gre_date %>
</p>

<%= link_to 'Edit', edit_userdetail_path(@userdetail) %> |
<%= link_to 'Back', userdetails_path %>