config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/topics')

  resources :topics do
    resources :posts
  end

  resources :userdetails

  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/post.rb
class Post < ActiveRecord::Base
  #relation between topics and post
  belongs_to :topic

  belongs_to :user

  #post is valid only if it's associated with a topic:

   validates :topic_id, :presence => true
  #can also require that the referenced topic itself be valid
  #in order for the post to be valid:

  validates_associated :topic



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_user
  before_filter :has_userdetail_and_topic, :only =>[:new, :create]



  # GET /posts
  # GET /posts.json

  #for new association SAAS book

  protected
  def has_userdetail_and_topic

    unless(@topic =Topic.find_by_id(params[:topic_id]))
      flash[:warning] = 'post must be for an existing topic'
    end
  end

  public

  def new
    @post = @topic.posts.build
    #@@topic = Topic.find(params[:topic_id1])

  end

  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new


  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = @topic.posts.build(post_params)
    current_user.posts << @post


    #current_user.posts << @topic.posts.build(params[post_params])

    #@topic.posts << @post

    #@post = Post.new(post_params )

    #@post.userdetail_id = current_user.id

     #Association functional between topic and post
     #Class variable used
     #@@topic.posts << @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to [@topic, @post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:topic_id,:issue, :description, :rating, :user_id )
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
  		

  		<%= label :post, :description %>
		<%= text_area :post, :description %>
			

app/views/posts/edit.html.erb
<div class="row">

<div class="col-md-4">

</div>

<div class="col-md-4">


			<h1>Editing post</h1>

			<%= render 'form' %>

			<%= link_to 'Show', @post %> |
			<%= link_to 'Back', posts_path %>

</div> 

<div class="col-md-4">
</div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-2">


  </div>
  <div class="col-md-8">

          <h1>Listing posts</h1>

          
        <table class="table">
            <thead>
              <tr>
                <th>User</th>
                <th>Issue</th>
                <th>Description</th>
                <th>Rating</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @posts.each do |post| %>
                <tr>
                  <td><%= post.user_id %></td>
                  <td><%= post.issue %></td>
                  <td><%= post.description %></td>
                  <td><%= post.rating %></td>
<% 
=begin %>
                 

                 <td><%= link_to 'Show', @post %></td>
                    <td><%= link_to 'Edit', edit_post_path(post) %></td> 
                     <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
                </tr>
                <% 
=end %>
              <% end %>
            </tbody>
          </table>

          <br>


  </div>

  <div class="col-md-2">


  </div>

</div>

app/views/posts/new.html.erb
<div class="row">

<div class="col-md-4">

</div>

  <div class="col-md-4">




		<%= form_tag topic_posts_path(@topic) do  %>
		    <%= render 'form' %>
		    <%= submit_tag 'Create post' %>

		<%end%>

    




</div> 

  <div class="col-md-4">
</div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issue:</strong>
  <%= @post.issue %>
</p>

<p>

  <strong>Topic_id:</strong>
  <%= @post.topic_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @post.rating %>
</p>

<!--< link_to 'Edit', edit_topic_post_path([@topic, @post]) %> | -->
<!--< link_to 'Back', posts_path %>-->